ALTER DATABASE [TST02]
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

USE [master]
RESTORE DATABASE [TST02] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL13.DYNAMICS02\MSSQL\Backup\<CHANGE_ME>.bak' WITH  FILE = 1,  MOVE N'GPSMAX01Dat.mdf' TO N'C:\Program Files\Microsoft SQL Server\MSSQL13.DYNAMICS02\MSSQL\DATA\GPSTST02Dat.mdf',  MOVE N'GPSMAX01Log.ldf' TO N'C:\Program Files\Microsoft SQL Server\MSSQL13.DYNAMICS02\MSSQL\DATA\GPSTST02Log.ldf',  NOUNLOAD,  REPLACE,  STATS = 5

GO


